"""Excel (XlsxWriter) and PDF (WeasyPrint) exports of a report (FR-31).

Times are shown in each row's employee timezone; minutes as h:mm. PDF is meant for reading and printing,
so it is capped; Excel always contains every row.
"""

import io
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

from facetrack_common.constants import AttendanceStatus
from jinja2 import Environment, FileSystemLoader, select_autoescape

from app.schemas.report import ReportColumn, ReportOut

PDF_MAX_ROWS = 5_000
_TEMPLATES = Environment(
    loader=FileSystemLoader(Path(__file__).parent / "templates"),
    autoescape=select_autoescape(["html"]),
)
_STATUS_LABELS = {
    AttendanceStatus.PRESENT: "Present",
    AttendanceStatus.LATE: "Late",
    AttendanceStatus.EARLY_EXIT: "Early exit",
    AttendanceStatus.HALF_DAY: "Half day",
    AttendanceStatus.ABSENT: "Absent",
    AttendanceStatus.ON_LEAVE: "On leave",
    AttendanceStatus.HOLIDAY: "Holiday",
    AttendanceStatus.WEEKLY_OFF: "Weekly off",
    AttendanceStatus.MISSING_CHECKOUT: "Missing check-out",
}


def format_minutes(minutes: int | None) -> str:
    if minutes is None:
        return ""
    return f"{minutes // 60}:{minutes % 60:02d}"


def format_cell(column: ReportColumn, row: dict[str, Any], default_tz: str) -> str:
    """Text for one cell, as shown in exports."""
    value = row.get(column.key)
    if value is None or value == "":
        return ""
    if column.kind == "time":
        tz = ZoneInfo(str(row.get("_tz") or default_tz))
        return datetime.fromisoformat(str(value)).astimezone(tz).strftime("%H:%M")
    if column.kind == "minutes":
        return format_minutes(int(value))
    if column.kind == "status":
        try:
            return _STATUS_LABELS[AttendanceStatus(value)]
        except ValueError:
            return str(value)
    if column.kind == "bool":
        return "Yes" if value else ""
    if column.kind == "date":
        return datetime.fromisoformat(str(value)).strftime("%d-%m-%Y")
    return str(value)


def _sanitize(text: str) -> str:
    """Spreadsheet formula injection: text starting with = + - @ is shown literally."""
    return f"'{text}" if text[:1] in ("=", "+", "-", "@") else text


def _meta(report: ReportOut, filters_text: str, generated_by: str) -> list[tuple[str, str]]:
    return [
        ("Report", report.title),
        ("Period", f"{report.date_from:%d-%m-%Y} to {report.date_to:%d-%m-%Y}"),
        ("Filters", filters_text or "None"),
        (
            "Generated",
            f"{datetime.now(UTC).astimezone(ZoneInfo(report.timezone)):%d-%m-%Y %H:%M} ({report.timezone})",
        ),
        ("Generated by", generated_by),
    ]


def to_xlsx(report: ReportOut, filters_text: str, generated_by: str) -> bytes:
    import xlsxwriter  # noqa: PLC0415  # heavy; only the worker needs it

    buffer = io.BytesIO()
    workbook = xlsxwriter.Workbook(buffer, {"in_memory": True, "strings_to_formulas": False})
    bold = workbook.add_format({"bold": True})
    header = workbook.add_format({"bold": True, "bg_color": "#E2E8F0", "border": 1})
    sheet = workbook.add_worksheet(report.title[:31])
    row = 0
    for label, value in _meta(report, filters_text, generated_by):
        sheet.write(row, 0, label, bold)
        sheet.write_string(row, 1, value)
        row += 1
    row += 1
    for col, column in enumerate(report.columns):
        sheet.write(row, col, column.label, header)
        width = (
            6
            if column.kind == "letter"
            else 12
            if column.kind in ("time", "minutes", "count", "bool")
            else 22
        )
        sheet.set_column(col, col, width)
    header_row = row
    for record in report.rows:
        row += 1
        for col, column in enumerate(report.columns):
            text = format_cell(column, record, report.timezone)
            if not text:
                continue  # empty cells stay empty, so Excel filters on "(Blanks)" work
            if column.kind == "count":
                sheet.write_number(row, col, float(text))
            else:
                sheet.write_string(row, col, _sanitize(text))
    if report.rows:
        sheet.autofilter(header_row, 0, row, len(report.columns) - 1)
    sheet.freeze_panes(header_row + 1, 0)

    summary = workbook.add_worksheet("Summary")
    for index, item in enumerate(report.summary):
        summary.write(index, 0, item.label, bold)
        shown = format_minutes(int(item.value)) if item.kind == "minutes" else item.value
        if isinstance(shown, (int, float)):
            summary.write_number(index, 1, shown)
        else:
            summary.write_string(index, 1, str(shown))
    summary.set_column(0, 0, 24)
    workbook.close()
    return buffer.getvalue()


def to_pdf(report: ReportOut, filters_text: str, generated_by: str) -> bytes:
    from weasyprint import HTML  # noqa: PLC0415  # heavy; only the worker needs it

    rows = report.rows[:PDF_MAX_ROWS]
    html = _TEMPLATES.get_template("report.html").render(
        report=report,
        meta=_meta(report, filters_text, generated_by),
        columns=report.columns,
        rows=[[format_cell(c, r, report.timezone) for c in report.columns] for r in rows],
        summary=[
            (item.label, format_minutes(int(item.value)) if item.kind == "minutes" else item.value)
            for item in report.summary
        ],
        omitted=len(report.rows) - len(rows),
        wide=len(report.columns) > 14,
    )
    return bytes(HTML(string=html).write_pdf())
