"""Excel (XlsxWriter) and PDF (WeasyPrint) exports of a report (FR-31), and Excel exports of list views.

Times are shown in each row's employee timezone; minutes as h:mm. PDF is meant for reading and printing,
so it is capped; Excel always contains every row. Every sheet uses the portal's status colours (styles.py).
"""

import io
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

from facetrack_common.constants import AttendanceStatus
from jinja2 import Environment, FileSystemLoader, select_autoescape

from app.domain.reports.styles import (
    BORDER,
    BRAND,
    HEADER_TEXT,
    LEGEND,
    LETTER_TONES,
    META_FILL,
    TONE_COLOURS,
    ZEBRA_FILL,
    status_tone,
)
from app.schemas.report import ReportColumn, ReportOut, Tone

PDF_MAX_ROWS = 5_000
_TEMPLATES = Environment(
    loader=FileSystemLoader(Path(__file__).parent / "templates"),
    autoescape=select_autoescape(["html"]),
)
_STATUS_LABELS = {
    AttendanceStatus.PRESENT: "Present",
    AttendanceStatus.LATE: "Late",
    AttendanceStatus.EARLY_EXIT: "Early exit",
    AttendanceStatus.HALF_DAY: "Half day",
    AttendanceStatus.ABSENT: "Absent",
    AttendanceStatus.ON_LEAVE: "On leave",
    AttendanceStatus.HOLIDAY: "Holiday",
    AttendanceStatus.WEEKLY_OFF: "Weekly off",
    AttendanceStatus.MISSING_CHECKOUT: "Missing check-out",
}


def format_minutes(minutes: int | None) -> str:
    if minutes is None:
        return ""
    return f"{minutes // 60}:{minutes % 60:02d}"


def format_cell(column: ReportColumn, row: dict[str, Any], default_tz: str) -> str:
    """Text for one cell, as shown in exports."""
    value = row.get(column.key)
    if value is None or value == "":
        return ""
    if column.kind == "time":
        tz = ZoneInfo(str(row.get("_tz") or default_tz))
        return datetime.fromisoformat(str(value)).astimezone(tz).strftime("%H:%M")
    if column.kind == "minutes":
        return format_minutes(int(value))
    if column.kind == "status":
        try:
            return _STATUS_LABELS[AttendanceStatus(value)]
        except ValueError:
            return str(value)
    if column.kind == "bool":
        return "Yes" if value else ""
    if column.kind == "date":
        return datetime.fromisoformat(str(value)).strftime("%d-%m-%Y")
    return str(value)


def _sanitize(text: str) -> str:
    """Spreadsheet formula injection: text starting with = + - @ is shown literally."""
    return f"'{text}" if text[:1] in ("=", "+", "-", "@") else text


def _meta(report: ReportOut, filters_text: str, generated_by: str) -> list[tuple[str, str]]:
    return [
        ("Report", report.title),
        ("Period", f"{report.date_from:%d-%m-%Y} to {report.date_to:%d-%m-%Y}"),
        ("Filters", filters_text or "None"),
        (
            "Generated",
            f"{datetime.now(UTC).astimezone(ZoneInfo(report.timezone)):%d-%m-%Y %H:%M} ({report.timezone})",
        ),
        ("Generated by", generated_by),
    ]


def cell_tone(column: ReportColumn, row: dict[str, Any], text: str) -> Tone | None:
    """Status colour of one cell: attendance status columns and register letters (§13)."""
    if column.kind == "status":
        return status_tone(row.get(column.key))
    if column.kind == "letter":
        return LETTER_TONES.get(text)
    return None


class _Formats:
    """XlsxWriter formats of one workbook, made once and reused (a workbook has a format limit)."""

    def __init__(self, workbook: Any) -> None:
        border = {"border": 1, "border_color": BORDER, "valign": "vcenter"}
        self._workbook = workbook
        self._border = border
        self.title = workbook.add_format({"bold": True, "font_size": 15, "font_color": BRAND})
        self.meta_label = workbook.add_format(
            {"bold": True, "bg_color": META_FILL, "font_color": BRAND, **border}
        )
        self.meta_value = workbook.add_format({"bg_color": META_FILL, **border})
        self.header = workbook.add_format(
            {"bold": True, "bg_color": BRAND, "font_color": HEADER_TEXT, "text_wrap": True, **border}
        )
        self._cells: dict[tuple[str | None, bool], Any] = {}

    def cell(self, tone: str | None, zebra: bool) -> Any:
        key = (tone, zebra)
        if key not in self._cells:
            spec: dict[str, Any] = dict(self._border)
            if tone is not None:
                fill, text = TONE_COLOURS[tone]
                spec |= {"bg_color": fill, "font_color": text, "bold": True, "align": "center"}
            elif zebra:
                spec["bg_color"] = ZEBRA_FILL
            self._cells[key] = self._workbook.add_format(spec)
        return self._cells[key]


Cell = tuple[str | float | None, Tone | None]


def _write_heading(sheet: Any, formats: _Formats, title: str, meta: list[tuple[str, str]]) -> int:
    """Title and meta block; returns the first free row."""
    sheet.set_row(0, 24)
    sheet.write_string(0, 0, f"FaceTrack — {title}", formats.title)
    for offset, (label, value) in enumerate(meta, start=1):
        sheet.write_string(offset, 0, label, formats.meta_label)
        sheet.write_string(offset, 1, _sanitize(value), formats.meta_value)
    return len(meta) + 2


def _write_table(
    sheet: Any,
    formats: _Formats,
    header_row: int,
    headers: list[str],
    widths: list[int],
    rows: list[list[Cell]],
) -> None:
    for col, (label, width) in enumerate(zip(headers, widths, strict=True)):
        sheet.write_string(header_row, col, label, formats.header)
        sheet.set_column(col, col, width)
    sheet.set_row(header_row, 30)
    row = header_row
    for index, cells in enumerate(rows):
        row += 1
        zebra = index % 2 == 1
        for col, (value, tone) in enumerate(cells):
            style = formats.cell(tone, zebra)
            if value is None or value == "":
                sheet.write_blank(row, col, None, style)  # stays empty, so "(Blanks)" filters work
            elif isinstance(value, (int, float)):
                sheet.write_number(row, col, value, style)
            else:
                sheet.write_string(row, col, _sanitize(value), style)
    if rows:
        sheet.autofilter(header_row, 0, row, len(headers) - 1)
    sheet.freeze_panes(header_row + 1, 0)


def _write_summary(sheet: Any, formats: _Formats, title: str, items: list[tuple[str, Cell]]) -> None:
    sheet.set_column(0, 0, 44)
    sheet.set_column(1, 1, 16)
    sheet.set_row(0, 24)
    sheet.write_string(0, 0, f"Summary — {title}", formats.title)
    sheet.write_string(2, 0, "Item", formats.header)
    sheet.write_string(2, 1, "Value", formats.header)
    row = 2
    for index, (label, (value, tone)) in enumerate(items):
        row += 1
        sheet.write_string(row, 0, label, formats.cell(tone, index % 2 == 1))
        style = formats.cell(tone, index % 2 == 1)
        if isinstance(value, (int, float)):
            sheet.write_number(row, 1, value, style)
        else:
            sheet.write_string(row, 1, "" if value is None else str(value), style)
    row += 2
    sheet.write_string(row, 0, "Colour legend", formats.header)
    for label, tone in LEGEND:
        row += 1
        sheet.write_string(row, 0, label, formats.cell(tone, False))


def _report_width(column: ReportColumn) -> int:
    if column.kind == "letter":
        return 5
    return 12 if column.kind in ("time", "minutes", "count", "bool", "status", "date") else 24


def _workbook(buffer: io.BytesIO) -> Any:
    import xlsxwriter  # noqa: PLC0415  # heavy; only the worker and the export route need it

    return xlsxwriter.Workbook(buffer, {"in_memory": True, "strings_to_formulas": False})


def to_xlsx(report: ReportOut, filters_text: str, generated_by: str) -> bytes:
    buffer = io.BytesIO()
    workbook = _workbook(buffer)
    formats = _Formats(workbook)
    sheet = workbook.add_worksheet(report.title[:31])
    header_row = _write_heading(sheet, formats, report.title, _meta(report, filters_text, generated_by))
    rows: list[list[Cell]] = []
    for record in report.rows:
        cells: list[Cell] = []
        for column in report.columns:
            text = format_cell(column, record, report.timezone)
            if not text:
                cells.append((None, None))
            elif column.kind == "count":
                cells.append((float(text), None))
            else:
                cells.append((text, cell_tone(column, record, text)))
        rows.append(cells)
    _write_table(
        sheet,
        formats,
        header_row,
        [c.label for c in report.columns],
        [_report_width(c) for c in report.columns],
        rows,
    )
    items: list[tuple[str, Cell]] = []
    for item in report.summary:
        shown = format_minutes(int(item.value)) if item.kind == "minutes" else item.value
        items.append((item.label, (shown if isinstance(shown, (int, float)) else str(shown), None)))
    _write_summary(workbook.add_worksheet("Summary"), formats, report.title, items)
    workbook.close()
    return buffer.getvalue()


def sheet_to_xlsx(
    title: str, headers: list[str], rows: list[list[Cell]], generated: str, generated_by: str
) -> bytes:
    """A list view exported as it is shown, with its status colours (§13 "export on every list", Q62)."""
    buffer = io.BytesIO()
    workbook = _workbook(buffer)
    formats = _Formats(workbook)
    sheet = workbook.add_worksheet(title[:31])
    meta = [("Generated", generated), ("Generated by", generated_by), ("Rows", str(len(rows)))]
    header_row = _write_heading(sheet, formats, title, meta)
    widths = []
    for col, header in enumerate(headers):
        longest = max((len(str(r[col][0])) for r in rows[:500] if r[col][0] is not None), default=0)
        widths.append(min(max(len(header), longest, 6) + 2, 50))
    _write_table(sheet, formats, header_row, headers, widths, rows)
    # Summary: how many rows carry each coloured value, per column (e.g. Status: Recognised 12).
    counts: dict[tuple[str, str, Tone], int] = {}
    for cells in rows:
        for col, (value, tone) in enumerate(cells):
            if tone is not None and value not in (None, ""):
                key = (headers[col], str(value), tone)
                counts[key] = counts.get(key, 0) + 1
    items: list[tuple[str, Cell]] = [("Rows", (len(rows), None))]
    items += [(f"{header}: {value}", (count, tone)) for (header, value, tone), count in counts.items()]
    _write_summary(workbook.add_worksheet("Summary"), formats, title, items)
    workbook.close()
    return buffer.getvalue()


def to_pdf(report: ReportOut, filters_text: str, generated_by: str) -> bytes:
    from weasyprint import HTML  # noqa: PLC0415  # heavy; only the worker needs it

    rows = report.rows[:PDF_MAX_ROWS]
    cells = []
    for record in rows:
        texts = [format_cell(c, record, report.timezone) for c in report.columns]
        pairs = zip(report.columns, texts, strict=True)
        cells.append([(t, cell_tone(c, record, t) if t else None) for c, t in pairs])
    html = _TEMPLATES.get_template("report.html").render(
        report=report,
        meta=_meta(report, filters_text, generated_by),
        columns=report.columns,
        rows=cells,
        tones=TONE_COLOURS,
        brand=BRAND,
        legend=LEGEND,
        summary=[
            (item.label, format_minutes(int(item.value)) if item.kind == "minutes" else item.value)
            for item in report.summary
        ],
        omitted=len(report.rows) - len(rows),
        wide=len(report.columns) > 14,
    )
    return bytes(HTML(string=html).write_pdf())
