"""initial schema: the sixteen tables of requirements §11 (ADR-0001 embeddings as ciphertext)

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 19:13:22.528876+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector stays available (ADR-0001), although embeddings are stored encrypted, not as vectors.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_clients')),
    sa.UniqueConstraint('key_prefix', name=op.f('uq_api_clients_key_prefix'))
    )
    op.create_table('departments',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('manager_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_manager_user_id'), 'departments', ['manager_user_id'], unique=False)
    op.create_index('uq_departments_code_live', 'departments', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('locations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index('uq_locations_name_live', 'locations', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_settings_key'))
    )
    op.create_table('shifts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_in_min', sa.Integer(), nullable=False),
    sa.Column('grace_out_min', sa.Integer(), nullable=False),
    sa.Column('half_day_pct', sa.Integer(), nullable=False),
    sa.Column('is_night_shift', sa.Boolean(), nullable=False),
    sa.Column('weekly_offs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    op.create_index('uq_shifts_name_live', 'shifts', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('cameras',
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rtsp_url_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('substream_url_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('engine_node', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('operating_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('role', sa.Enum('ENTRY', 'EXIT', 'ENTRY_EXIT', 'GENERAL', name='camera_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('roi_polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('match_threshold', sa.Float(), nullable=True),
    sa.Column('liveness_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'online', 'offline', 'disabled', name='camera_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_cameras_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_index('ix_cameras_engine_node', 'cameras', ['engine_node'], unique=False)
    op.create_index('uq_cameras_name_live', 'cameras', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('shift_id', sa.BigInteger(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='employee_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('consent_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hr_external_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_employees_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_employees_shift_id_shifts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_employees_employee_code')),
    sa.UniqueConstraint('hr_external_id', name=op.f('uq_employees_hr_external_id'))
    )
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_location_id'), 'employees', ['location_id'], unique=False)
    op.create_index(op.f('ix_employees_shift_id'), 'employees', ['shift_id'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_table('holidays',
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_holidays_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays'))
    )
    op.create_index(op.f('ix_holidays_location_id'), 'holidays', ['location_id'], unique=False)
    op.create_index('uq_holidays_location_date_live', 'holidays', ['location_id', 'date'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('attendance_days',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.BigInteger(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_event_id', sa.BigInteger(), nullable=True),
    sa.Column('check_out_event_id', sa.BigInteger(), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('present', 'late', 'early_exit', 'half_day', 'absent', 'on_leave', 'holiday', 'weekly_off', 'missing_checkout', name='attendance_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_days_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_attendance_days_shift_id_shifts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_days')),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_attendance_days_employee_work_date')
    )
    op.create_index('ix_attendance_days_work_date_status', 'attendance_days', ['work_date', 'status'], unique=False)
    op.create_table('face_enrollments',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('embedding_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('upload', 'webcam', 'review', name='enrollment_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_face_enrollments_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_enrollments'))
    )
    op.create_index(op.f('ix_face_enrollments_employee_id'), 'face_enrollments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_face_enrollments_model_name'), 'face_enrollments', ['model_name'], unique=False)
    op.create_table('leaves',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Enum('hr', 'manual', name='leave_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leaves_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaves'))
    )
    op.create_index('ix_leaves_employee_dates', 'leaves', ['employee_id', 'from_date', 'to_date'], unique=False)
    op.create_index('uq_leaves_external_ref_live', 'leaves', ['external_ref'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND external_ref IS NOT NULL'))
    op.create_table('users',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.Enum('local', 'ldap', name='auth_provider', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'hr_admin', 'department_manager', 'operator', 'employee', name='user_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_users_employee_id_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_users_employee_id'))
    )
    op.create_index('uq_users_email_live', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_users_username_live', 'users', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # departments -> users -> employees -> departments is a cycle: this FK is added once users exists.
    op.create_foreign_key(
        op.f('fk_departments_manager_user_id_users'), 'departments', 'users', ['manager_user_id'], ['id'],
        ondelete='SET NULL',
    )
    op.create_table('attendance_corrections',
    sa.Column('attendance_day_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=False),
    sa.Column('field', sa.Enum('check_in_at', 'check_out_at', 'status', name='correction_field', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('old_value', sa.String(length=64), nullable=True),
    sa.Column('new_value', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='correction_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_attendance_corrections_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attendance_day_id'], ['attendance_days.id'], name=op.f('fk_attendance_corrections_attendance_day_id_attendance_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_attendance_corrections_requested_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_corrections'))
    )
    op.create_index(op.f('ix_attendance_corrections_attendance_day_id'), 'attendance_corrections', ['attendance_day_id'], unique=False)
    op.create_index('ix_attendance_corrections_status_created', 'attendance_corrections', ['status', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('recognition_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_uuid', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('recognized', 'unknown', 'voided', name='recognition_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('track_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_path', sa.String(length=512), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('engine_node', sa.String(length=64), nullable=False),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.Column('voided_by', sa.BigInteger(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_recognition_events_camera_id_cameras'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_recognition_events_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], name=op.f('fk_recognition_events_voided_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'captured_at', name=op.f('pk_recognition_events')),
    sa.UniqueConstraint('event_uuid', 'captured_at', name='uq_recognition_events_event_uuid'),
    postgresql_partition_by='RANGE (captured_at)'
    )
    # Monthly partitions around "now" plus a DEFAULT partition, so an event is never rejected even if
    # the maintenance task (ensure_event_partitions) falls behind (NFR-7).
    op.execute(
        """
        DO $$
        DECLARE month_start date;
        BEGIN
            FOR offset_months IN -1..3 LOOP
                month_start := (date_trunc('month', now()) + make_interval(months => offset_months))::date;
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF recognition_events FOR VALUES FROM (%L) TO (%L)',
                    'recognition_events_' || to_char(month_start, 'YYYY_MM'),
                    month_start, (month_start + interval '1 month')::date
                );
            END LOOP;
        END $$;
        """
    )
    op.execute("CREATE TABLE IF NOT EXISTS recognition_events_default PARTITION OF recognition_events DEFAULT")
    op.create_index('ix_recognition_events_camera_captured', 'recognition_events', ['camera_id', 'captured_at'], unique=False)
    op.create_index('ix_recognition_events_employee_captured', 'recognition_events', ['employee_id', 'captured_at'], unique=False)
    op.create_index('ix_recognition_events_status_captured', 'recognition_events', ['status', 'captured_at'], unique=False)
    op.create_table('unknown_faces',
    sa.Column('recognition_event_id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('camera_id', sa.BigInteger(), nullable=False),
    sa.Column('embedding_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('snapshot_path', sa.String(length=512), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'assigned', 'dismissed', name='review_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('assigned_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], name=op.f('fk_unknown_faces_assigned_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_unknown_faces_camera_id_cameras'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_unknown_faces_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unknown_faces'))
    )
    op.create_index(op.f('ix_unknown_faces_recognition_event_id'), 'unknown_faces', ['recognition_event_id'], unique=False)
    op.create_index('ix_unknown_faces_review_captured', 'unknown_faces', ['review_status', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_departments_manager_user_id_users'), 'departments', type_='foreignkey')
    op.drop_index('ix_unknown_faces_review_captured', table_name='unknown_faces')
    op.drop_index(op.f('ix_unknown_faces_recognition_event_id'), table_name='unknown_faces')
    op.drop_table('unknown_faces')
    op.drop_index('ix_recognition_events_status_captured', table_name='recognition_events')
    op.drop_index('ix_recognition_events_employee_captured', table_name='recognition_events')
    op.drop_index('ix_recognition_events_camera_captured', table_name='recognition_events')
    op.drop_table('recognition_events')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attendance_corrections_status_created', table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_attendance_day_id'), table_name='attendance_corrections')
    op.drop_table('attendance_corrections')
    op.drop_index('uq_users_username_live', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_users_email_live', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_index('uq_leaves_external_ref_live', table_name='leaves', postgresql_where=sa.text('deleted_at IS NULL AND external_ref IS NOT NULL'))
    op.drop_index('ix_leaves_employee_dates', table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_face_enrollments_model_name'), table_name='face_enrollments')
    op.drop_index(op.f('ix_face_enrollments_employee_id'), table_name='face_enrollments')
    op.drop_table('face_enrollments')
    op.drop_index('ix_attendance_days_work_date_status', table_name='attendance_days')
    op.drop_table('attendance_days')
    op.drop_index('uq_holidays_location_date_live', table_name='holidays', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_holidays_location_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_shift_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_location_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index('uq_cameras_name_live', table_name='cameras', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_cameras_engine_node', table_name='cameras')
    op.drop_table('cameras')
    op.drop_index('uq_shifts_name_live', table_name='shifts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('shifts')
    op.drop_table('settings')
    op.drop_index('uq_locations_name_live', table_name='locations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('locations')
    op.drop_index('uq_departments_code_live', table_name='departments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_departments_manager_user_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('api_clients')
    # ### end Alembic commands ###
